feat(tooltipcondensed): add component, stories and tests
chanzuckerberg/sci-components pull request #150
Opened 2022-03-18 18:32 UTC by mdjmoore

## Summary

**Structural Element (Gene)**
Shortcut ticket: [sh-152183](https://app.shortcut.com/sci-design-system/story/152183/implement-tooltipcondensed-component-for-sds)
**Props**
- `indicator`: true | false;
- `indicatorColor`: string

## Checklist

- [x] Default Story in Storybook
- [x] LivePreview Story in Storybook
- [x] Test Story in Storybook
- [x] Tests written
- [x] Variables from `defaultTheme.ts` used wherever possible
- [x] If updating an existing component, depreciate flag has been used where necessary
- [ ] Chromatic build verified by @chanzuckerberg/sds-design

2022-03-18 20:36 UTC, mmmmmmaya commented on src/core/TooltipCondensed/style.ts
> +    && {
omg, TIL. so cool!

2022-03-18 20:38 UTC, mmmmmmaya approved these changes

2022-04-04 19:13 UTC, clarsen-czi requested changes
See my comments in Chromatic; there's a delay on hover that needs to be addressed.

2022-04-04 20:08 UTC, clarsen-czi approved these changes
Looks great, Meagan. Thanks for the quick fix!

2022-04-04 20:16 UTC, merged