feat(Row): Table Row component implementation
chanzuckerberg/sci-components pull request #242
Opened 2022-08-18 01:53 UTC by masoudmanson

## Summary

**Row**
Shortcut ticket: [sh-208408](https://app.shortcut.com/sci-design-system/story/208408/row-component)

Implemented with &lt;tr&gt; under the hood.

## Checklist

- [ ] Default Story in Storybook
- [ ] LivePreview Story in Storybook
- [ ] Test Story in Storybook
- [ ] Tests written
- [ ] Variables from `defaultTheme.ts` used wherever possible
- [ ] If updating an existing component, depreciate flag has been used where necessary
- [ ] Chromatic build verified by @chanzuckerberg/sds-design

2022-08-19 19:14 UTC, clarsen-czi requested changes
Just a small change regarding how row hovering is executed, but otherwise looking good!

2022-08-22 20:40 UTC, mmmmmmaya commented on src/core/Row/index.tsx
> +
```suggestion
```

2022-08-22 20:40 UTC, mmmmmmaya approved these changes

2022-08-25 18:22 UTC, bethbertozzi commented on src/core/Row/index.test.tsx
> +});
could increase test coverage to include rendering of other props, like hover

2022-08-31 21:48 UTC, clarsen-czi reviewed
LGTM! Thanks @masoudmanson !

2022-09-01 01:55 UTC, merged