feat(cellbasic): add icon support to CellBasic
chanzuckerberg/sci-components pull request #262
Opened 2022-09-15 21:27 UTC by masoudmanson

2022-09-15 21:57 UTC, bethbertozzi requested changes
I think it would be good to have a test with the icon, but other than that and a small cleanup it looks really great 😃 thanks Masoud!

2022-09-15 21:57 UTC, bethbertozzi commented on src/core/CellBasic/index.stories.tsx
> +    },
add icon as control to exclude in test

2022-09-16 14:22 UTC, bethbertozzi approved these changes
looks great!

2022-09-16 14:22 UTC, bethbertozzi commented on src/core/CellBasic/index.test.tsx
> +
🙌

2022-09-16 18:45 UTC, clarsen-czi approved these changes
LGTM! Thanks @masoudmanson !!

2022-09-16 18:52 UTC, merged