feat(inputcheckbox): add optional caption
chanzuckerberg/sci-components pull request #276
Opened 2022-10-25 03:19 UTC by bethbertozzi

## Summary

**Input Checkbox**
Shortcut ticket: [sh-204074](https://app.shortcut.com/sci-design-system/story/204074/add-caption-to-checkbox-component)
Add functionality and update like preview linked below. Caption should be optional.

## Checklist

- [ ] Default Story in Storybook
- [ ] LivePreview Story in Storybook
- [ ] Test Story in Storybook
- [ ] Tests written
- [ ] Variables from `defaultTheme.ts` used wherever possible
- [ ] If updating an existing component, depreciate flag has been used where necessary
- [ ] Chromatic build verified by @chanzuckerberg/sds-design

2022-10-27 19:06 UTC, clarsen-czi requested changes
Looking good @bethbertozzi ! The only change is there should be the option to add a caption

2022-10-28 16:32 UTC, bethbertozzi commented
@clarsen-czi I coded it so if the caption prop is empty, it is removed 👍

2022-11-07 15:55 UTC, masoudmanson approved these changes
Awesome, Thank you @bethbertozzi

2022-11-07 15:55 UTC, masoudmanson commented on src/core/InputCheckbox/index.tsx
> +      <div>Conetnes</div>
I think this is a typo!

2022-11-07 18:42 UTC, clarsen-czi approved these changes
Thanks for clarifying the functionality of the caption @bethbertozzi . This LGTM!!

2022-11-07 20:16 UTC, merged