feat(NavigationFooter): implement NavigationFooter component
chanzuckerberg/sci-components pull request #886
Opened 2024-10-30 17:32 UTC by codemonkey800

## Summary

Github issue: #817

Implements NavigationFooter component for desktop and mobile

## Checklist

- [x] Default Story in Storybook
- [x] LivePreview Story in Storybook
- [x] Test Story in Storybook
- [x] Tests written
- [x] Variables from `defaultTheme.ts` used wherever possible
- [x] If updating an existing component, depreciate flag has been used where necessary
- [x] Chromatic build verified by @chanzuckerberg/sds-design

2024-10-30 20:09 UTC, kev-zunshiwang commented
Thanks Jeremy! Most feedback are similar to the header feedback, except the image slot one is new.

Logo Slot
- Update color to Base/border for the dash border line around "logo slot"
- Unbold the text "logo slot"
- The entire area of "logo slot / logo name / beta tag" should be linked to the home page of the product. Not sure if this affects the code
Tag
- Update text inside the tags to title case
- Remove the hover effect for the tags
Image slot
- each image should have a link to the designated home page of that logo
- Update the "person" minimal button to a icon button (see design for the specific spec)

2024-10-30 20:34 UTC, kev-zunshiwang commented
Mobile Feedback
Logo
- whole area should be a link
Nav item
- On hover, bold the text with Narrow/fontBodyS/600

2024-12-04 16:29 UTC, tihuan approved these changes
LGTM! Thanks so much for adding this, @codemonkey800 🎉 !! Right in time for VCP to use 🙏 🙏 🙏 

Not a blocker, but IIRC many SDS components are wrapped in `forwardRef()` not sure if it makes sense to do it here too as a followup PR 😄 

Thanks again!!

2024-12-04 23:56 UTC, clarsen-czi requested changes
Looking good @codemonkey800!! Added a few comments of things to adjust, but they're mostly small tweaks so hopefully should be straight forward. Feel free to reach out with any questions though!

2025-02-27 21:40 UTC, masoudmanson approved these changes

2025-02-27 21:50 UTC, tihuan approved these changes
LGTM! Thanks again for adding all the tests to make the component robust 🙏 ✨ !! So thorough!!

2025-02-27 22:19 UTC, clarsen-czi requested changes
Looking good @masoudmanson! Got a few changes to make, but we're getting close

2025-02-27 23:33 UTC, clarsen-czi requested changes
Just two small changes and then we should be good!!

2025-02-27 23:48 UTC, merged