refactor(callout): new hideTitle and hideBody props and a component slot
chanzuckerberg/sci-components pull request #910
Opened 2024-11-26 18:57 UTC by masoudmanson

## Summary

**Callout**
Github issue: #909 

Refactor the `Callout` component with the following updates:

- Add a component slot for `extraContent`, allowing additional content to be placed at the bottom of the `Callout` component.
- Introduce two new props to toggle the visibility of the `calloutTitle` and `calloutText`.

## Checklist

- [ ] Default Story in Storybook
- [ ] LivePreview Story in Storybook
- [ ] Test Story in Storybook
- [ ] Tests written
- [ ] Variables from `defaultTheme.ts` used wherever possible
- [ ] If updating an existing component, depreciate flag has been used where necessary
- [ ] Chromatic build verified by @chanzuckerberg/sds-design

2024-12-04 21:55 UTC, clarsen-czi requested changes
Looks great @masoudmanson! Once you get the alignment of the title with the icon when there's no body text updated it will be good to go

2024-12-10 23:12 UTC, masoudmanson commented
> Looks great @masoudmanson! Once you get the alignment of the title with the icon when there's no body text updated it will be good to go

Thanks so much, @clarsen-czi! I’ve updated the title styles. Let me know if they need further refactoring or if we’re good to go! 🥳🎉🙏🏻

2024-12-11 18:07 UTC, clarsen-czi approved these changes
Looks great, @masoudmanson! Thanks for the fix!

2024-12-17 17:48 UTC, tihuan approved these changes
Looks fantastic! Thanks so much for the upgrade, @masoudmanson 🤩 🙏 

Just one small non blocking discussion 😁 Thanks again!

2024-12-18 21:07 UTC, masoudmanson commented on packages/components/src/core/Callout/components/CalloutExtraContent/style.ts
> +      margin: ${!hideTitle || !hideBody ? spaces?.m : 0}px 0 0 0;
Ahh, you’re absolutely right 🤣 My code does look funny 😱🤣 Thanks for catching that, @tihuan! 
Always learning from you 🥳😍

2024-12-18 21:20 UTC, merged

2024-12-18 23:34 UTC, tihuan commented on packages/components/src/core/Callout/components/CalloutExtraContent/style.ts
> +      margin: ${!hideTitle || !hideBody ? spaces?.m : 0}px 0 0 0;
You too!! Thanks again for the great work 😄 👏 🥇 ❤️